Algoritmo "consumo"

Var
   DistanciaPercorrida : inteiro
   CombustivelGasto, ConsumoMedio : real
   
Inicio

    escreva ("Distancia percorrida: ")
    leia (DistanciaPercorrida)
    escreva ("Combustível gasto: ")
    leia (CombustivelGasto)
    
    ConsumoMedio <-  DistanciaPercorrida / CombustivelGasto
    escreva ("Consumo medio = ", ConsumoMedio:8:3)
    
    


Fimalgoritmo