Algoritmo "crescente"

Var
   x, y : inteiro


Inicio


    escreval ("Digite dois numeros: ")
    leia (x)
    leia (y)
    
     enquanto x <> y faca
     
     se x < y entao
     
        escreval ("CRESCENTE")
    senao
     escreval ("DECRESCENTE")
    fimse

    escreval ("Digite outros dois numeros: ")
    leia (x)
    leia (y)
     //se  (x = y) e ( y = x)   entao

     fimenquanto
     
    Fimalgoritmo





